---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ibm-spectrum-scale-csi-driver

resources:
- ../../rbac/
- ../../manager/
- ../../crd/

patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=ibm-spectrum-scale-csi-operator"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ibm-spectrum-scale-csi-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                image: quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator@sha256:6ba22a73ed93ca8a62852e795ccf40b4793143f71e6f1e3d1224217d00de7592
                env:
                  - name: METRICS_BIND_ADDRESS
                  - name: WATCH_NAMESPACE
                  - name: CSI_DRIVER_IMAGE
                    value: quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:35c2c45c0a8f6504cf50dda57fd0c827244e822e02febf449a37630fc6d01b9d
