---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ibm-spectrum-scale-csi-driver

resources:
- ../../rbac/
- ../../manager/
- ../../crd/

patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=ibm-spectrum-scale-csi-operator"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ibm-spectrum-scale-csi-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:a82dbfe3d4e21a32ce24d19d2be968617c85c0568e8b2257d49efe1479111ac5
                env:
                  - name: METRICS_BIND_ADDRESS
                  - name: WATCH_NAMESPACE
                  - name: CSI_DRIVER_IMAGE
                    value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:6309f857e1bcf0f2a01a945295bfbc8d1a10e55ee50204736a99bdc387640e95
